-- INSERT INTO historico.propietarios (ci, nombres, apellidos, fecha_nacimiento) VALUES ("1048", "Jose", "Peñat", "1999-05-30");
--
-- INSERT INTO historico.carros (marca, modelo, color, placa, anio, precio) VALUES ("Ford", "Mustang", "Rojo", "ADF-1121", 2017, 59000);
-- INSERT INTO historico.carros (marca, modelo, color, placa, anio, precio) VALUES ("Nissan", "Leaf", "Blanco", "SSJ-3002", 2014, 29000);
-- INSERT INTO historico.carros (marca, modelo, color, placa, anio, precio) VALUES ("Toyota", "Prius", "Silver", "KKO-0212", 2018, 39000);